### PR TITLE
meter character is overlapped when distance is Infinity

### PR DESCRIPTION
**Pull request by thangins**
screenshot_20170106-100556

### CODE REVIEW

**Comment by Bridouille** [comment]
Hi, I'm curious to know how did you get an "Infinity" distance, is it very far, very close, a special value (so that I can reproduce it) ?

However, according to material design the margin & paddings should be multiple of 8, I'm thinking 88 should replace 85.

**Comment by thangins** [comment]
iBeacon is closed to me, its rssi is about -70dBm

**Comment by Bridouille** [comment]
My preferred solution would be to know where the 'infinity' comes from and avoid it (might be from the float formatting), it doesn't even make sense to display and "infinite" distance.

I'll have a look at it soon.

**Comment by Bridouille** [comment]
Thanks for updating your comment with more infos, I'm going to change the layout :)

**Comment by Bridouille** [comment]
The commit e58f9380ea7a983f38c425825fb8f729d5967fec should have fixed the issue 👍

**Pull request closed without merging**
